### ISSUE TITLE
Import consola in dev plugin

### ISSUE THREAD

**Issue by yottybyte** [artmizu/yandex-metrika-nuxt#4]
<img width="1261" alt="Снимок экрана 2023-03-22 в 16 47 28" src="https://user-images.githubusercontent.com/39698457/226924267-d656772e-74e4-4c3e-a67a-769a8f7e6786.png">

replace:
import consola from 'consola'
by
import consola from 'consola/src/browser'

consola docs https://www.npmjs.com/package/consola

**Comment by artmizu** [comment]
But the overall bundle size can be improved, i did it here

thank you for feedback
